
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.cawezsmantletostratus.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.entity.MobCategory;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.Entity;
import net.minecraft.core.registries.Registries;

import net.mcreator.cawezsmantletostratus.entity.TorchProjectileEntity;
import net.mcreator.cawezsmantletostratus.entity.PoisonDartEntity;
import net.mcreator.cawezsmantletostratus.CawezsMantleToStratusMod;

public class CawezsMantleToStratusModEntities {
	public static final DeferredRegister<EntityType<?>> REGISTRY = DeferredRegister.create(Registries.ENTITY_TYPE, CawezsMantleToStratusMod.MODID);
	public static final DeferredHolder<EntityType<?>, EntityType<PoisonDartEntity>> POISON_DART = register("poison_dart",
			EntityType.Builder.<PoisonDartEntity>of(PoisonDartEntity::new, MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));
	public static final DeferredHolder<EntityType<?>, EntityType<TorchProjectileEntity>> TORCH_PROJECTILE = register("torch_projectile",
			EntityType.Builder.<TorchProjectileEntity>of(TorchProjectileEntity::new, MobCategory.MISC).setShouldReceiveVelocityUpdates(true).setTrackingRange(64).setUpdateInterval(1).sized(0.5f, 0.5f));

	// Start of user code block custom entities
	// End of user code block custom entities
	private static <T extends Entity> DeferredHolder<EntityType<?>, EntityType<T>> register(String registryname, EntityType.Builder<T> entityTypeBuilder) {
		return REGISTRY.register(registryname, () -> (EntityType<T>) entityTypeBuilder.build(registryname));
	}
}
