package net.mcreator.cawezsmantletostratus.procedures;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.util.RandomSource;
import net.minecraft.util.Mth;
import net.minecraft.core.BlockPos;

public class ExhumedAirAdditionalGenerationConditionProcedure {
	public static boolean execute(LevelAccessor world, double x, double y, double z) {
		for (int index0 = 0; index0 < 128; index0++) {
			if( !world.getBlockState(BlockPos.containing(x, index0, z)).canOcclude()) {

				if (Mth.nextInt(RandomSource.create(), 1, 100)<95) {
					
					world.setBlock(BlockPos.containing(x, index0, z), Blocks.RED_NETHER_BRICK_WALL.defaultBlockState(), 3);
				} else {
					world.setBlock(BlockPos.containing(x, index0, z), Blocks.PEARLESCENT_FROGLIGHT.defaultBlockState(), 3);
				}
			}
		}
		return true;
	}
}
