/*
 * The code of this mod element is always locked.
 *
 * You can register new events in this class too.
 *
 * If you want to make a plain independent class, create it using
 * Project Browser -> New... and make sure to make the class
 * outside net.mcreator.cawezsmantletostratus as this package is managed by MCreator.
 *
 * If you change workspace package, modid or prefix, you will need
 * to manually adapt this file to these changes or remake it.
 *
 * This class will be added in the mod root package.
*/
package net.mcreator.cawezsmantletostratus;

import net.neoforged.neoforge.event.server.ServerStartingEvent;
import net.neoforged.fml.event.lifecycle.FMLCommonSetupEvent;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.api.distmarker.Dist;

@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD)
public class Notes {
	public Notes() {
	}

	@SubscribeEvent
	public static void init(FMLCommonSetupEvent event) {
		new Notes();
	}

	@OnlyIn(Dist.CLIENT)
	@SubscribeEvent
	public static void clientLoad(FMLClientSetupEvent event) {
	}

	@EventBusSubscriber
	private static class NotesForgeBusEvents {
		@SubscribeEvent
		public static void serverLoad(ServerStartingEvent event) {
		}
	}
}

/*
 * 
 
    "settings": {
      "name": "cawezs_mantle_to_stratus:heights",
      "sea_level": 0,
      "legacy_random_source": true,
      "disable_mob_generation": false,
      "aquifers_enabled": false,
      "ore_veins_enabled": false,
      "default_block": {
        "Name": "minecraft:tuff"
      },
      "default_fluid": {
        "Name": "minecraft:water",
        "Properties": {
          "level": "0"
        }
      },
      "spawn_target": [],
      "noise": {
        "min_y": 0,
        "height": 256,
        "size_horizontal": 2,
        "size_vertical": 1,
        "island_noise_override": true
      },
      "noise_router": {
        "barrier": 0,
        "fluid_level_floodedness": 0,
        "fluid_level_spread": 0,
        "lava": 0,
        "temperature": 0,
        "vegetation": 0,
        "continents": 0,
        "erosion": {
          "type": "minecraft:cache_2d",
          "argument": {
            "type": "minecraft:end_islands"
          }
        },
        "depth": 0,
        "ridges": 0,
        "initial_density_without_jaggedness": {
          "type": "minecraft:add",
          "argument1": -0.234375,
          "argument2": {
            "type": "minecraft:mul",
            "argument1": {
              "type": "minecraft:y_clamped_gradient",
              "from_y": 4,
              "to_y": 32,
              "from_value": 0,
              "to_value": 1
            },
            "argument2": {
              "type": "minecraft:add",
              "argument1": 0.234375,
              "argument2": {
                "type": "minecraft:add",
                "argument1": -23.4375,
                "argument2": {
                  "type": "minecraft:mul",
                  "argument1": {
                    "type": "minecraft:y_clamped_gradient",
                    "from_y": 200,
                    "to_y": 312,
                    "from_value": 1,
                    "to_value": 0
                  },
                  "argument2": {
                    "type": "minecraft:add",
                    "argument1": 23.4375,
                    "argument2": {
                      "type": "minecraft:add",
                      "argument1": -10.0,
                      "argument2": {
                        "type": "minecraft:cache_2d",
                        "argument": {
                          "type": "minecraft:end_islands"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "final_density": {
          "type": "minecraft:squeeze",
          "argument": {
            "type": "minecraft:mul",
            "argument1": 0.64,
            "argument2": {
              "type": "minecraft:interpolated",
              "argument": {
                "type": "minecraft:blend_density",
                "argument": {
                  "type": "minecraft:add",
                  "argument1": -0.234375,
                  "argument2": {
                    "type": "minecraft:mul",
                    "argument1": {
                      "type": "minecraft:y_clamped_gradient",
                      "from_y": 4,
                      "to_y": 32,
                      "from_value": 0,
                      "to_value": 1
                    },
                    "argument2": {
                      "type": "minecraft:add",
                      "argument1": 0.234375,
                      "argument2": {
                        "type": "minecraft:add",
                        "argument1": -23.4375,
                        "argument2": {
                          "type": "minecraft:mul",
                          "argument1": {
                            "type": "minecraft:y_clamped_gradient",
                            "from_y": 200,
                            "to_y": 312,
                            "from_value": 1,
                            "to_value": 0
                          },
                          "argument2": {
                            "type": "minecraft:add",
                            "argument1": 23.0,
                            "argument2": "minecraft:end/sloped_cheese"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "vein_toggle": 0,
        "vein_ridged": 0,
        "vein_gap": 0
      },
      */
