
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.cawezsmantletostratus.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.cawezsmantletostratus.CawezsMantleToStratusMod;

public class CawezsMantleToStratusModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, CawezsMantleToStratusMod.MODID);
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MT_S = REGISTRY.register("mt_s",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.cawezs_mantle_to_stratus.mt_s")).icon(() -> new ItemStack(CawezsMantleToStratusModBlocks.HAELIUM.get())).displayItems((parameters, tabData) -> {
				tabData.accept(CawezsMantleToStratusModBlocks.HAELIUM.get().asItem());
				tabData.accept(CawezsMantleToStratusModBlocks.AMINALITE.get().asItem());
				tabData.accept(CawezsMantleToStratusModBlocks.SOLITITE.get().asItem());
				tabData.accept(CawezsMantleToStratusModBlocks.FORTITE.get().asItem());
				tabData.accept(CawezsMantleToStratusModBlocks.OBSIDILITE.get().asItem());
				tabData.accept(CawezsMantleToStratusModBlocks.CELERITITE.get().asItem());
				tabData.accept(CawezsMantleToStratusModItems.HAELIUM_GEMSTONE.get());
				tabData.accept(CawezsMantleToStratusModItems.AMINALITE_GEMSTONE.get());
				tabData.accept(CawezsMantleToStratusModItems.SOLITITE_GEMSTONE.get());
				tabData.accept(CawezsMantleToStratusModItems.FORTITE_GEMSTONE.get());
				tabData.accept(CawezsMantleToStratusModItems.CELERITITE_GEMSTONE.get());
				tabData.accept(CawezsMantleToStratusModItems.OBSIDILITE_GEMSTONE.get());
				tabData.accept(CawezsMantleToStratusModItems.ESSENCE_AERIS.get());
				tabData.accept(CawezsMantleToStratusModItems.ESSENCE_STORM.get());
				tabData.accept(CawezsMantleToStratusModItems.ESSENCE_OVERGROWTH.get());
				tabData.accept(CawezsMantleToStratusModItems.ESSENCE_GRIMSTONE.get());
				tabData.accept(CawezsMantleToStratusModItems.ESSENCE_GLOOM.get());
				tabData.accept(CawezsMantleToStratusModItems.ESSENCE_ICHOR.get());
				tabData.accept(CawezsMantleToStratusModItems.BLOOD_GLOOM.get());
				tabData.accept(CawezsMantleToStratusModItems.BLOOD_ICHOR.get());
				tabData.accept(CawezsMantleToStratusModItems.BLOOD_AERIS.get());
				tabData.accept(CawezsMantleToStratusModItems.BLOOD_GRIMSTONE.get());
				tabData.accept(CawezsMantleToStratusModItems.BLOOD_OVERGROWTH.get());
				tabData.accept(CawezsMantleToStratusModItems.BLOOD_STORM.get());
				tabData.accept(CawezsMantleToStratusModItems.ROSE_AMULET.get());
				tabData.accept(CawezsMantleToStratusModItems.ROUGE_AMULET.get());
				tabData.accept(CawezsMantleToStratusModItems.AMBER_AMULET.get());
				tabData.accept(CawezsMantleToStratusModItems.COBALT_AMULET.get());
				tabData.accept(CawezsMantleToStratusModItems.AZURE_AMULTE.get());
				tabData.accept(CawezsMantleToStratusModItems.JADE_AMULET.get());
				tabData.accept(CawezsMantleToStratusModItems.BURIED_ARMOR_HELMET.get());
				tabData.accept(CawezsMantleToStratusModItems.BURIED_ARMOR_CHESTPLATE.get());
				tabData.accept(CawezsMantleToStratusModItems.BURIED_ARMOR_LEGGINGS.get());
				tabData.accept(CawezsMantleToStratusModItems.BURIED_ARMOR_BOOTS.get());
				tabData.accept(CawezsMantleToStratusModItems.HEAVEN_ARMOR_HELMET.get());
				tabData.accept(CawezsMantleToStratusModItems.HEAVEN_ARMOR_CHESTPLATE.get());
				tabData.accept(CawezsMantleToStratusModItems.HEAVEN_ARMOR_LEGGINGS.get());
				tabData.accept(CawezsMantleToStratusModItems.HEAVEN_ARMOR_BOOTS.get());
				tabData.accept(CawezsMantleToStratusModItems.VERGLAS_LABRYS.get());
				tabData.accept(CawezsMantleToStratusModItems.FINISHER.get());
				tabData.accept(CawezsMantleToStratusModItems.ECLARIS_STAFF.get());
				tabData.accept(CawezsMantleToStratusModItems.PHANTOM_SWORD.get());
				tabData.accept(CawezsMantleToStratusModItems.BANISHER.get());
				tabData.accept(CawezsMantleToStratusModItems.WAND_OF_LIGHT.get());
				tabData.accept(CawezsMantleToStratusModItems.STARFORGED_PICKAXE.get());
				tabData.accept(CawezsMantleToStratusModItems.ABSORBER.get());
				tabData.accept(CawezsMantleToStratusModItems.EYE_CANON.get());
				tabData.accept(CawezsMantleToStratusModItems.DIURNAL_CONTROLLER.get());
			}).build());
}
