package net.mcreator.cawezsmantletostratus.procedures;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.util.RandomSource;
import net.minecraft.util.Mth;
import net.minecraft.core.BlockPos;
public class StarlightAdditionalGenerationConditionProcedure {
	public static boolean execute(LevelAccessor world, double x, double y, double z) {

		for (int i = 100; i < 256; i++) {

			if ((world.getBlockState(BlockPos.containing(x, i, z))).getBlock() == Blocks.AIR && (world.getBlockState(BlockPos.containing(x, i+1, z))).getBlock() != Blocks.AIR) {
				world.setBlock(BlockPos.containing(x, i, z), Blocks.END_ROD.defaultBlockState(), 3);
				return true;
			}

		}
		return true;

	}
}
