/*
 * The code of this mod element is always locked.
 *
 * You can register new events in this class too.
 *
 * If you want to make a plain independent class, create it using
 * Project Browser -> New... and make sure to make the class
 * outside net.mcreator.cawezsmantletostratus as this package is managed by MCreator.
 *
 * If you change workspace package, modid or prefix, you will need
 * to manually adapt this file to these changes or remake it.
 *
 * This class will be added in the mod root package.
*/
package net.mcreator.cawezsmantletostratus;

import net.neoforged.neoforge.event.server.ServerStartingEvent;
import net.neoforged.fml.event.lifecycle.FMLCommonSetupEvent;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.api.distmarker.Dist;

@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD)
public class Notes {
	public Notes() {
	}

	@SubscribeEvent
	public static void init(FMLCommonSetupEvent event) {
		new Notes();
	}

	@OnlyIn(Dist.CLIENT)
	@SubscribeEvent
	public static void clientLoad(FMLClientSetupEvent event) {
	}

	@EventBusSubscriber
	private static class NotesForgeBusEvents {
		@SubscribeEvent
		public static void serverLoad(ServerStartingEvent event) {
		}
	}
}

/*
 * 
 
    "settings": {
      "name": "cawezs_mantle_to_stratus:depths",
      "sea_level": 21,
      "legacy_random_source": true,
      "disable_mob_generation": false,
      "aquifers_enabled": false,
      "ore_veins_enabled": true,
      "default_block": {
        "Name": "minecraft:blackstone"
      },
      "default_fluid": {
        "Name": "minecraft:obsidian"
      },
      "spawn_target": [],
      "noise": {
        "min_y": 0,
        "height": 256,
        "size_horizontal": 1,
        "size_vertical": 2
      },
      "noise_router": {
        "barrier": 0,
        "fluid_level_floodedness": 0,
        "fluid_level_spread": 0,
        "lava": 0,
        "temperature": {
          "type": "minecraft:shifted_noise",
          "noise": "minecraft:temperature",
          "xz_scale": 0.25,
          "y_scale": 0,
          "shift_x": "minecraft:shift_x",
          "shift_y": "minecraft:shift_y",
          "shift_z": "minecraft:shift_z"
        },
        "vegetation": {
          "type": "minecraft:shifted_noise",
          "noise": "minecraft:vegetation",
          "xz_scale": 0.25,
          "y_scale": 0,
          "shift_x": "minecraft:shift_x",
          "shift_y": "minecraft:shift_y",
          "shift_z": "minecraft:shift_z"
        },
        "continents": 0,
        "erosion": 0,
        "depth": 0,
        "ridges": 0,
        "initial_density_without_jaggedness": 0,
        "final_density": {
          "type": "minecraft:squeeze",
          "argument": {
            "type": "minecraft:mul",
            "argument1": 0.2,
            "argument2": {
              "type": "minecraft:interpolated",
              "argument": {
                "type": "minecraft:blend_density",
                "argument": {
                  "type": "minecraft:add",
                  "argument1": 2.5,
                  "argument2": {
                    "type": "minecraft:mul",
                    "argument1": {
                      "type": "minecraft:y_clamped_gradient",
                      "from_y": -8,
                      "to_y": 24,
                      "from_value": 0,
                      "to_value": 1
                    },
                    "argument2": {
                      "type": "minecraft:add",
                      "argument1": -2.5,
                      "argument2": {
                        "type": "minecraft:add",
                        "argument1": 0.9375,
                        "argument2": {
                          "type": "minecraft:mul",
                          "argument1": {
                            "type": "minecraft:y_clamped_gradient",
                            "from_y": 246,
                            "to_y": 256,
                            "from_value": 1,
                            "to_value": 0
                          },
                          "argument2": {
                            "type": "minecraft:add",
                            "argument1": -0.9375,
                            "argument2": "minecraft:nether/base_3d_noise"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "vein_toggle": 0,
        "vein_ridged": 0,
        "vein_gap": 0
      },
      */
