
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.cawezsmantletostratus.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.cawezsmantletostratus.CawezsMantleToStratusMod;

public class CawezsMantleToStratusModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, CawezsMantleToStratusMod.MODID);
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MT_S = REGISTRY.register("mt_s",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.cawezs_mantle_to_stratus.mt_s")).icon(() -> new ItemStack(Blocks.POINTED_DRIPSTONE)).displayItems((parameters, tabData) -> {
				tabData.accept(CawezsMantleToStratusModBlocks.FOSSIL.get().asItem());
			})

					.build());
}
