package net.mcreator.cawezsmantletostratus.procedures;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.core.BlockPos;

public class CliffTorchAdditionalGenerationConditionProcedure {
	public static boolean execute(LevelAccessor world, double x, double y, double z) {
		world.setBlock(BlockPos.containing(x, 1 + y, z), Blocks.LIGHT.defaultBlockState(), 3);
		world.setBlock(BlockPos.containing(x, 0 + y, z), Blocks.TORCHFLOWER.defaultBlockState(), 3);
		return true;
	}
}
