
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.cawezsmantletostratus.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.cawezsmantletostratus.CawezsMantleToStratusMod;

public class CawezsMantleToStratusModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(CawezsMantleToStratusMod.MODID);
	public static final DeferredItem<Item> BASE_GROUND = block(CawezsMantleToStratusModBlocks.BASE_GROUND);
	public static final DeferredItem<Item> HAELIUM = block(CawezsMantleToStratusModBlocks.HAELIUM);
	public static final DeferredItem<Item> AMINALITE = block(CawezsMantleToStratusModBlocks.AMINALITE);
	public static final DeferredItem<Item> SOLITITE = block(CawezsMantleToStratusModBlocks.SOLITITE);
	public static final DeferredItem<Item> FORTITE = block(CawezsMantleToStratusModBlocks.FORTITE);
	public static final DeferredItem<Item> OBSIDILITE = block(CawezsMantleToStratusModBlocks.OBSIDILITE);
	public static final DeferredItem<Item> CELERITITE = block(CawezsMantleToStratusModBlocks.CELERITITE);

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
